# Generated by Django 4.2.3 on 2023-08-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='articulo/6.jpg', null=True, upload_to='articulo'),
        ),
    ]
