# Generated by Django 4.2.2 on 2023-08-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='nickname',
        ),
    ]
