# Generated by Django 4.2.3 on 2023-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='static/6.jpg', null=True, upload_to='posts'),
        ),
    ]
