# Generated by Django 4.2.3 on 2023-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_articulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='media/articulo/default_articulo.jpg', null=True, upload_to='posts'),
        ),
    ]
