# Generated by Django 4.2.3 on 2023-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='static/default_articulo.jpg', null=True, upload_to='articulo'),
        ),
    ]
